// routes/student-auth.js
// Owns: student account login (temp password token from CRM) and session management.
// Does NOT own: student account creation (done by CRM), password reset, email verification.
// Access: public — no auth required.
const sa = require('../db/student-accounts');

module.exports = function createStudentAuthRouter({ pool }) {
  const router = require('express').Router();

  // ── POST /api/student-auth/login ──────────────────────────────────────────
  // Login using temp password token (generated by CRM and shown once to DIRECTRICE).
  // Body: { token, password }
  router.post('/login', async (req, res) => {
    try {
      const { token, password } = req.body;
      if (!token || !password) {
        return res.status(400).json({ error: 'Token et mot de passe requis' });
      }

      const student = await sa.validateStudentTempToken(pool, token, password);
      if (!student) {
        return res.status(401).json({ error: 'Code ou mot de passe temporaire invalide ou expiré' });
      }

      // Consume the temp token (mark as used)
      const crypto = require('crypto');
      const tokenHash = crypto.createHash('sha256').update(token).digest('hex');
      await pool.query(
        `UPDATE auth_tokens SET used = true
         WHERE token_hash = $1 AND type = 'student_temp_pwd'`,
        [tokenHash]
      );

      // Create student session
      const sessionToken = await sa.createStudentSession(pool, student.id);

      // Check if blocked
      const blocked = await sa.isBlocked(pool, student.id);

      res.json({
        token: sessionToken,
        student: {
          id: student.id,
          student_id: student.student_id,
          first_name: student.first_name,
          last_name: student.last_name,
          email: student.email,
          is_blocked: blocked,
        }
      });
    } catch (err) {
      console.error('[student-auth] POST /login error:', err);
      res.status(500).json({ error: 'Erreur serveur' });
    }
  });

  // ── POST /api/student-auth/logout ──────────────────────────────────────────
  router.post('/logout', async (req, res) => {
    try {
      const auth = req.headers.authorization;
      if (auth && auth.startsWith('Bearer ')) {
        await sa.invalidateStudentSession(pool, auth.slice(7));
      }
      res.json({ ok: true });
    } catch (err) {
      console.error('[student-auth] POST /logout error:', err);
      res.status(500).json({ error: 'Erreur serveur' });
    }
  });

  return router;
};